### ISSUE TITLE
执行查询实体类属性映射出错

### ISSUE THREAD

**Issue by m310851010** [subchen/jetbrick-orm#1]
**调用代码如下,**
`DbHelper dbHelper = new DbHelper(dataSource);`
`String sql = "SELECT n_id id, c_name name, n_age age, n_create_time createTime FROM t_user";`
`List<User> list = dbHelper.queryAsList(new BeanRowMapper<User>(User.class), sql);`

实体类User和sql中的别名相同

**错误堆栈如下:**
`jetbrick.dao.DbException: java.sql.SQLException: Can't set bean property.
    sql = [SELECT n_id id, c_name name, n_age age, n_create_time createTime FROM t_user]
    parameters = [[]]
    at jetbrick.dao.orm.DbHelper.query(DbHelper.java:214)
    at jetbrick.dao.orm.DbHelper.queryAsList(DbHelper.java:106)
    at com.mdc.orm.DbHelperTet.queryList(DbHelperTet.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.sql.SQLException: Can't set bean property.
    at jetbrick.dao.orm.mapper.BeanRowMapper.handle(BeanRowMapper.java:60)
    at jetbrick.dao.orm.handler.RowListHandler.handle(RowListHandler.java:41)
    at jetbrick.dao.orm.handler.RowListHandler.handle(RowListHandler.java:1)
    at jetbrick.dao.orm.DbHelper.query(DbHelper.java:212)
    ... 25 more
Caused by: java.lang.NullPointerException
    at jetbrick.dao.orm.mapper.BeanRowMapper.handle(BeanRowMapper.java:54)
    ... 28 more`

**Comment by subchen** [comment]
看错误，应该是 User 里面没有找到 setXXX 方法导致的问题。
1. 试试升级 jetbrick-commons.jar
2. 给出 User.java 完整的代码我看看

如果方法1不能解决问题的话，应该就是一个bug了

**Comment by BigSnake1989** [comment]
有完整的文档说明，或者实例吗
orm 能和 template 结合吗，如果有复杂的sql,还是需要像mybaits-xml配置的写法

**Comment by subchen** [comment]
暂时没有详细的文档，主要接口就是 `DbHelper.queryXXX()`

下面代码 `dbHelper.queryAsList(new BeanRowMapper<User>(User.class), sql)` 
可以简化为：`dbHelper.queryAsList(User.class， sql)`

orm 可以和模板结合的，而且任何sql映射都是用的默认命名转换规则，无需xml配置

**Comment by subchen** [comment]
那个错误应该是 `createTime` 字段映射错误把，映射规则是驼峰转换，所以sql中应该用 `create_time` 而java中用`createTime`

**Comment by subchen** [comment]
那个错误应该是 `createTime` 字段映射错误把，映射规则是驼峰转换，所以sql中应该用 `create_time` 而java中用`createTime`
